# .github/workflows/build.yml
name: Build WhisperTray

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ created ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            artifact: whisper-tray
            experimental: true
          - os: macos-latest
            goos: darwin
            goarch: arm64
            artifact: whisper-tray
            experimental: false
          - os: windows-latest
            goos: windows
            goarch: amd64
            artifact: whisper-tray.exe
            experimental: true

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: true

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev libx11-dev xorg-dev libxtst-dev

    - name: Install macOS dependencies
      if: runner.os == 'macOS'
      run: |
        brew install portaudio

    - name: Cache whisper.cpp
      uses: actions/cache@v4
      with:
        path: vendor/whisper.cpp
        key: ${{ runner.os }}-whisper-v1.5.4-${{ hashFiles('**/Makefile') }}

    - name: Build whisper.cpp
      run: make whisper-cpp
      shell: bash

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

    - name: Build application
      run: make build-mac
      if: runner.os == 'macOS'
      shell: bash

    - name: Build application (Linux)
      if: runner.os == 'Linux'
      env:
        CGO_ENABLED: 1
      run: |
        CGO_CFLAGS="-I$(pwd)/vendor/whisper.cpp" \
        CGO_LDFLAGS="-L$(pwd)/vendor/whisper.cpp -lwhisper" \
        go build -ldflags="-s -w -X main.Version=${{ github.ref_name }} -X main.Commit=${{ github.sha }}" \
        -o bin/${{ matrix.artifact }} ./cmd/whisper-tray
      shell: bash

    - name: Build application (Windows)
      if: runner.os == 'Windows'
      env:
        CGO_ENABLED: 1
      run: |
        go build -ldflags="-s -w -X main.Version=${{ github.ref_name }} -X main.Commit=${{ github.sha }}" \
        -o bin/${{ matrix.artifact }} ./cmd/whisper-tray
      shell: bash

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: whisper-tray-${{ matrix.goos }}-${{ matrix.goarch }}
        path: bin/*

    - name: Create release archive
      if: github.event_name == 'release'
      run: |
        cd bin
        if [ "${{ runner.os }}" == "Windows" ]; then
          7z a whisper-tray-${{ matrix.goos }}-${{ matrix.goarch }}.zip *
        else
          tar czf whisper-tray-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz *
        fi
      shell: bash

    - name: Upload release assets
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: ./bin/whisper-tray-${{ matrix.goos }}-${{ matrix.goarch }}.*