# .github/workflows/build.yml
name: Build WhisperTray

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: true

    - name: Install macOS dependencies
      run: |
        brew install portaudio

    - name: Cache whisper.cpp
      uses: actions/cache@v4
      with:
        path: vendor/whisper.cpp
        key: macos-whisper-v1.5.4-${{ hashFiles('**/Makefile') }}

    - name: Build whisper.cpp
      run: make whisper-cpp
      shell: bash

    - name: Download dependencies
      run: go mod download

    - name: Build application
      run: make build
      shell: bash

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: whisper-tray-darwin-arm64
        path: bin/*

    - name: Create release archive
      if: github.event_name == 'release'
      run: |
        cd bin
        tar czf whisper-tray-darwin-arm64.tar.gz *
      shell: bash

    - name: Upload release assets
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: ./bin/whisper-tray-darwin-arm64.tar.gz