# .github/workflows/test.yml
name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: true

    - name: Install macOS dependencies
      run: |
        brew install portaudio

    - name: Cache whisper.cpp
      uses: actions/cache@v4
      with:
        path: vendor/whisper.cpp
        key: macos-whisper-v1.5.4-${{ hashFiles('**/Makefile') }}

    - name: Build whisper.cpp
      run: make whisper-cpp
      shell: bash

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: make test
      shell: bash