# .github/workflows/test.yml
name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            required: false
          - os: macos-latest
            goos: darwin
            required: true
          - os: windows-latest
            goos: windows
            required: false

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ !matrix.required }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: true

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev libx11-dev xorg-dev libxtst-dev

    - name: Install macOS dependencies
      if: runner.os == 'macOS'
      run: |
        brew install portaudio

    - name: Cache whisper.cpp
      uses: actions/cache@v4
      with:
        path: vendor/whisper.cpp
        key: ${{ runner.os }}-whisper-v1.5.4-${{ hashFiles('**/Makefile') }}

    - name: Build whisper.cpp
      run: make whisper-cpp
      shell: bash

    - name: Download dependencies
      run: go mod download

    - name: Run tests
      run: make test
      shell: bash